"""English UI catalog: Chinese source text -> English translation.

由翻译整理生成；key 必须与代码中的中文原文逐字一致（包括标点、空格、省略号、括号全半角）。
"""

EN: dict[str, str] = {
    # ------------------------------------------------------------ 应用与主窗口
    "工作小记": "WorkLog",
    "工作小记 · 工作记录与日报助手": "WorkLog · AI work log & daily report assistant",
    "工作小记已经在运行，请在系统托盘查看。": "WorkLog is already running. Check the system tray.",
    "{APP_NAME} · 工作记录与日报助手": "{APP_NAME} · AI work log & daily report assistant",
    " · 工作记录与日报助手": " · AI work log & daily report assistant",
    "工作记录与日报助手": "AI work log & daily report assistant",
    "记录中": "Recording",
    "已暂停": "Paused",
    "离开中": "Away",
    "AI 分析中": "Analyzing",
    "已停止": "Stopped",
    "异常": "Error",
    "立即记录": "Capture now",
    "暂停记录": "Pause recording",
    "继续记录": "Resume recording",
    "显示主窗口": "Show main window",
    "退出": "Quit",
    "已最小化到托盘，记录继续运行。": "Minimized to the tray; recording continues.",
    # ---------------------------------------------------------------- 导航与通用
    "今日": "Today",
    "时间线": "Timeline",
    "统计": "Stats",
    "报告": "Report",
    "待办": "To-dos",
    "设置": "Settings",
    "编辑": "Edit",
    "删除": "Delete",
    "保存": "Save",
    "取消": "Cancel",
    "添加": "Add",
    "复制": "Copy",
    "另存为": "Save as",
    "今天": "Today",
    "自定义": "Custom",
    "未知": "Unknown",
    "未分类": "Uncategorized",
    # -------------------------------------------------------------------- 今日页
    "今日概览": "Today",
    "尚未配置 AI，点这里选择服务商 →": "AI is not configured — click to choose a provider →",
    "生成今日日报": "Generate daily report",
    "记录条数": "Records",
    "专注时长": "Focus time",
    "活跃时段": "Active hours",
    "未完成待办": "Open to-dos",
    "今日时间线": "Today's timeline",
    "今天还没有记录。打开记录开关后，它会自动工作。": "No records yet today. Once recording is on, it works automatically.",
    "按记录时长估算": "Estimated from record durations",
    "首末活动时间": "First and last activity",
    "在待办页管理": "Manage on the To-dos page",
    "{date} · {n} 个片段": "{date} · {n} records",
    "{today} · {n} 个片段": "{today} · {n} records",
    "共采集 {n} 次": "Collected {n} times",
    "共采集 {hits} 次": "Collected {hits} times",
    # ------------------------------------------------------------------ 时间线页
    "重新分析未分析": "Re-analyze pending",
    "手动添加": "Add manually",
    "这一天还没有记录。": "No records for this day.",
    "· {n} 个片段": "· {n} records",
    "这一天没有待分析的记录。": "No pending records to analyze for this day.",
    "重新分析": "Re-analyze",
    "重新分析失败": "Re-analysis failed",
    "完成：{done}/{total} 条记录已补上分析。": "Done: {done}/{total} records analyzed.",
    "删除记录": "Delete record",
    "确定删除 {start} 的这条记录吗？": "Delete the record at {start}?",
    "确定删除 {time} 的这条记录吗？": "Delete the record at {time}?",
    "编辑记录": "Edit record",
    "手动添加记录": "Add record manually",
    # -------------------------------------------------------------------- 统计页
    "从": "From",
    "到": "To",
    "记录片段": "Records",
    "活跃天数": "Active days",
    "采集次数": "Captures",
    "最近 7 天": "Last 7 days",
    "本周": "This week",
    "本月": "This month",
    "有记录的天数": "Days with records",
    "自动采集次数": "Automatic captures",
    "应用使用时长": "App usage",
    "暂无应用数据": "No app data yet",
    "分类分布": "Categories",
    "暂无分类数据": "No category data yet",
    "时段热力图（周 × 小时）": "Activity heatmap (week × hour)",
    "高频标签": "Top tags",
    # -------------------------------------------------------------------- 报告页
    "日报": "Daily report",
    "周报": "Weekly report",
    "月报": "Monthly report",
    "历史报告": "Report history",
    "类型": "Type",
    "基准日期": "Reference date",
    "模板": "Template",
    "补充要求（可选），例如：语气更简洁": "Extra instructions (optional), e.g. keep it concise",
    "生成报告": "Generate report",
    "另存为 Markdown": "Save as Markdown",
    "打开报告目录": "Open reports folder",
    "选择左侧报告，或点击「生成报告」。": "Select a report on the left, or click Generate report.",
    "{label} 没有任何工作记录。": "{label} has no work records.",
    "没有可用模板。": "No template available.",
    "正在生成，请稍候…": "Generating, please wait…",
    "已生成并保存": "Generated and saved",
    "生成失败": "Generation failed",
    "已复制到剪贴板": "Copied to clipboard",
    "已保存": "Saved",
    "删除报告": "Delete report",
    "确定删除这份报告吗？": "Delete this report?",
    "已删除": "Deleted",
    "成果导向日报": "Outcome-focused Daily Report",
    "简洁流水日报": "Concise Daily Log",
    "标准周报": "Standard Weekly Report",
    "月度总结": "Monthly Summary",
    "{year}年{month}月": "{month}/{year}",
    "所选时间段内没有任何工作记录，无法生成报告。": "No work records in the selected period; cannot generate a report.",
    # -------------------------------------------------------------------- 待办页
    "截止": "Due",
    "截止 {date}": "Due {date}",
    "截止 {due}": "Due {due}",
    "添加待办，回车确认…": "Add a to-do, press Enter to confirm…",
    "从时间线提取待办：": "Extract to-dos from timeline:",
    "AI 提取": "Extract with AI",
    "还没有待办。可以手动添加，或让 AI 从时间线里提取。": "No to-dos yet. Add one manually, or let AI extract them from your timeline.",
    "· {done} 项未完成 / 共 {total} 项": "· {done} open / {total} total",
    "· {n} 项未完成 / 共 {total} 项": "· {n} open / {total} total",
    "手动": "Manual",
    "AI提取": "AI",
    "删除待办": "Delete to-do",
    "删除「{title}」？": "Delete “{title}”?",
    "提取待办": "Extract to-dos",
    "{date} 没有工作记录。": "No work records for {date}.",
    "{day} 没有工作记录。": "No work records for {day}.",
    "请先在「设置」里配置 AI 接口。": "Set up the AI provider in Settings first.",
    "正在提取…": "Extracting…",
    "提取到 {n} 条待办": "Extracted {n} to-dos",
    "提取到 {count} 条待办": "Extracted {count} to-dos",
    "没有提取到明确的待办": "No clear to-dos found",
    "提取失败": "Extraction failed",
    # -------------------------------------------------------------------- 设置页
    "界面语言 / Language": "Language",
    "语言": "Language",
    "自动 / Auto": "Auto",
    "AI 模型接口": "AI model API",
    "服务商": "Provider",
    "粘贴你的 API Key": "Paste your API key",
    "高级设置（接口地址、模型名等）": "Advanced settings (API URL, model names, etc.)",
    " 秒": " sec",
    "补充给模型的指令，例如：我在做电商项目，分类时把「直播」归到「运营」": "Extra instructions for the model, e.g. I work on an e-commerce project; classify “Live streaming” as “Operations”.",
    "接口地址": "API URL",
    "视觉模型": "Vision model",
    "文本模型": "Text model",
    "请求超时": "Request timeout",
    "截图最大宽度": "Max screenshot width",
    "JPEG 质量": "JPEG quality",
    "补充指令": "Extra instructions",
    "测试连接": "Test connection",
    "记录设置": "Recording",
    "所有屏幕（合成）": "All screens (combined)",
    "显示器 {n}": "Monitor {n}",
    "显示器 {index}": "Monitor {index}",
    "每行一个进程名，例如 Chrome.exe": "One process name per line, e.g. Chrome.exe",
    "启动应用后自动开始记录": "Start recording automatically when the app launches",
    "截屏间隔": "Capture interval",
    "截屏范围": "Capture source",
    "空闲多久后暂停": "Pause after idle",
    "排除的应用": "Excluded apps",
    "隐私": "Privacy",
    "· 截图只在内存中用于一次 AI 分析，分析结束立即销毁，不写入磁盘。\n· 工作记录、报告和待办保存在程序目录下的 data 文件夹，卸载时可选择保留或删除。\n· 只有分析请求会发送到你自己配置的模型接口。": "· Screenshots are used in memory for a single AI analysis and destroyed immediately afterwards — never written to disk.\n· Work records, reports and to-dos are stored in the data folder next to the app. You can keep or delete them when uninstalling.\n· Only analysis requests are sent to the model API you configure.",
    "在提示词中要求模型脱敏个人信息（推荐）": "Ask the model to redact personal information in prompts (recommended)",
    "本地 Agent API": "Local Agent API",
    "启用本地 API（仅 127.0.0.1 可访问）": "Enable local API (127.0.0.1 only)",
    "端口": "Port",
    "数据": "Data",
    "当前数据目录：{path}": "Current data folder: {path}",
    "打开数据目录": "Open data folder",
    "导出全部数据": "Export all data",
    "清空所有记录": "Clear all records",
    "关于与更新": "About & updates",
    "当前版本：v{version}": "Current version: v{version}",
    "检查更新": "Check for updates",
    "选择安装包升级": "Select installer to upgrade",
    "启动时自动检查更新（推荐）": "Check for updates at startup (recommended)",
    "更新源：GitHub Releases（内置，无需填写任何地址）": "Update source: GitHub Releases (built in; no URL needed)",
    "保存设置": "Save settings",
    "手动填写接口地址（以 /v1 结尾）和模型名，任何 OpenAI 兼容接口都可以。": "Enter the API URL (ending in /v1) and model names; any OpenAI-compatible API works.",
    "正在检查更新…": "Checking for updates…",
    "检查失败：{message}": "Check failed: {message}",
    "已是最新版本（v{version}）": "Up to date (v{version})",
    "发现新版本": "Update available",
    "发现新版本 v{remote}（当前 v{current}）": "New version v{remote} available (current: v{current})",
    "发现新版本 v{remote}，可稍后再更新": "New version v{remote} available; you can update later",
    "\n\n是否立即下载并自动安装？安装完成后程序会自动重新打开。": "\n\nDownload and install it now? The app will reopen automatically when done.",
    "更新清单缺少下载地址 url": "Update manifest is missing the download URL",
    "是否立即下载并自动安装？安装完成后程序会自动重新打开。": "Download and install it now? The app will reopen automatically when done.",
    "界面语言已更改": "Interface language changed",
    "需要重启应用才能生效，是否立即重启？": "Restart the app to apply the change. Restart now?",
    "{result}。确认无误后点「保存设置」": "{result}. If everything looks right, click Save settings.",
    "正在下载安装包…": "Downloading installer…",
    "正在下载新版本…": "Downloading new version…",
    "下载失败：{message}": "Download failed: {message}",
    "下载失败：{exc}": "Download failed: {exc}",
    "下载完成：{path}": "Downloaded: {path}",
    "选择新版本安装包": "Select a new version installer",
    "安装包 (*.exe)": "Installer (*.exe)",
    "自动更新": "Automatic update",
    "即将安装：\n{path}\n\n程序会先退出，安装完成后自动重新打开；工作数据会保留。\n\n继续吗？": "About to install:\n{path}\n\nThe app will quit first and reopen automatically when installation finishes. Your work data will be kept.\n\nContinue?",
    "即将安装：\n{installer}\n\n程序会先退出，安装完成后自动重新打开；工作数据会保留。\n\n继续吗？": "About to install:\n{installer}\n\nThe app will quit first and reopen automatically when installation finishes. Your work data will be kept.\n\nContinue?",
    "更新失败": "Update failed",
    "更新启动失败：{message}": "Failed to start update: {message}",
    "更新启动失败：{exc}": "Failed to start update: {exc}",
    "已保存（API 端口修改需重启应用）": "Saved (restart the app to apply API port changes)",
    "请先选择服务商或填写接口地址": "Choose a provider or enter an API URL first",
    "请先填写 API Key": "Enter your API key first",
    "测试中，请稍候…": "Testing, please wait…",
    "文本模型正常": "Text model OK",
    "视觉模型正常": "Vision model OK",
    "文本模型失败（{message}）": "Text model failed ({message})",
    "文本模型失败（{exc}）": "Text model failed ({exc})",
    "视觉模型失败（{message}）": "Vision model failed ({message})",
    "视觉模型失败（{exc}）": "Vision model failed ({exc})",
    "。确认无误后点「保存设置」": ". If everything looks right, click Save settings.",
    "失败：{message}": "Failed: {message}",
    "导出数据": "Export data",
    "已导出": "Exported",
    "将删除全部工作记录（报告和待办保留），且不可恢复。确定继续吗？": "This will delete all work records (reports and to-dos are kept) and cannot be undone. Continue?",
    "已清空所有记录": "All records cleared",
    # ---------------------------------------------------------- 通用组件与对话框
    "暂无数据": "No data yet",
    "暂无标签": "No tags yet",
    "暂无记录": "No records yet",
    "待分析": "Pending",
    "记": "W",
    "一句话说明做了什么": "Describe what you did in one sentence",
    "用逗号分隔，最多 3 个": "Comma-separated, up to 3",
    "开始时间": "Start time",
    "结束时间": "End time",
    "分类": "Category",
    "摘要": "Summary",
    "详情": "Details",
    "项目": "Project",
    "标签": "Tags",
    # ---------------------------------------------------------------- 统计与数据
    "{minutes} 分钟": "{minutes} min",
    "{hours} 小时 {minutes} 分": "{hours} h {minutes} min",
    "{hours} 小时": "{hours} h",
    "未知应用": "Unknown app",
    "屏幕活动": "Screen activity",
    "(无标题)": "(untitled)",
    "工作记录": "Work record",
    # ------------------------------------------------------------------ AI 服务商
    "DeepSeek（深度求索）": "DeepSeek",
    "通义千问（阿里云百炼）": "Qwen (Alibaba Cloud Model Studio)",
    "智谱 GLM": "Zhipu GLM",
    "硅基流动 SiliconFlow": "SiliconFlow",
    "Kimi（月之暗面）": "Kimi (Moonshot)",
    "火山方舟（豆包）": "Volcano Ark (Doubao)",
    "腾讯混元": "Tencent Hunyuan",
    "百度千帆（文心）": "Baidu Qianfan (ERNIE)",
    "OpenAI（ChatGPT）": "OpenAI (ChatGPT)",
    "本地 Ollama（离线免费）": "Local Ollama (offline, free)",
    "自定义（手动填写接口）": "Custom (manual setup)",
    "官方 API 已原生支持图片输入，国内直连、价格便宜；在 platform.deepseek.com 创建 API Key。": "The official API supports image input natively. Fast access from China and inexpensive; create an API key at platform.deepseek.com.",
    "在阿里云百炼控制台创建 API Key，新用户一般有免费额度，国内速度稳定。": "Create an API key in the Alibaba Cloud Model Studio console. New users usually get free quota, and speeds in China are stable.",
    "在 open.bigmodel.cn 创建 API Key；glm-4.5-flash 文本模型目前免费。": "Create an API key at open.bigmodel.cn; the glm-4.5-flash text model is currently free.",
    "在 siliconflow.cn 创建 API Key，注册通常送额度，国内可选模型多、便宜。": "Create an API key at siliconflow.cn. Sign-up usually includes free credit, with many affordable models available in China.",
    "在 platform.moonshot.cn 创建 API Key。": "Create an API key at platform.moonshot.cn.",
    "在火山方舟控制台创建 API Key；如果用接入点，把模型名换成 ep- 开头的接入点 ID。": "Create an API key in the Volcano Ark console. If you use an endpoint, replace the model name with the endpoint ID that starts with ep-.",
    "在腾讯云混元控制台创建 API Key。": "Create an API key in the Tencent Cloud Hunyuan console.",
    "在百度智能云千帆控制台创建 API Key。": "Create an API key in the Baidu AI Cloud Qianfan console.",
    "在 platform.openai.com 创建 API Key；gpt-4o-mini 便宜够用，国内访问可能需要代理。": "Create an API key at platform.openai.com; gpt-4o-mini is cheap and capable, but access from China may need a proxy.",
    "需要先安装 Ollama 并下载对应模型；数据完全不出本机，但比较吃显卡。API Key 随便填即可。": "Install Ollama and download the matching models first. Data never leaves your machine, but it needs a decent GPU. Any API key will do.",
    "随便填，例如 ollama": "Any value, e.g. ollama",
    "填写任何 OpenAI 兼容接口的地址（以 /v1 结尾）和模型名。": "Enter the URL (ending in /v1) and model names for any OpenAI-compatible API.",
    # ------------------------------------------------------- AI 客户端与错误提示
    "API Key 无效或未授权（HTTP 401）": "Invalid or unauthorized API key (HTTP 401)",
    "无权访问该模型（HTTP 403）": "Access to this model is forbidden (HTTP 403)",
    "接口地址或模型名不存在（HTTP 404）": "API URL or model name not found (HTTP 404)",
    "请求过于频繁或额度不足（HTTP 429）": "Too many requests or insufficient quota (HTTP 429)",
    "模型服务异常（HTTP {status}）": "Model service error (HTTP {status})",
    "接口返回错误（HTTP {status}）：{snippet}": "API error (HTTP {status}): {snippet}",
    "未配置 API 地址": "API URL not configured",
    "未配置 API Key": "API key not configured",
    "无法连接模型接口：{message}": "Cannot reach the model API: {message}",
    "无法连接模型接口：{exc}": "Cannot reach the model API: {exc}",
    "响应格式异常：{message}": "Unexpected response format: {message}",
    "响应格式异常：{exc}": "Unexpected response format: {exc}",
    "请求失败": "Request failed",
    "未配置更新地址": "No update URL configured",
    "更新清单格式不正确，需要包含 version 和 url 字段": "Invalid update manifest: it must contain version and url fields",
    "更新清单里缺少下载地址 url": "Update manifest is missing the download URL",
    "安装包不存在：{path}": "Installer not found: {path}",
    "安装包不存在：{installer}": "Installer not found: {installer}",
    # ------------------------------------------------------------------ 记录引擎
    "无法加载截图模块：{message}": "Failed to load the screen capture module: {message}",
    "无法加载截图模块：{exc}": "Failed to load the screen capture module: {exc}",
    "截图失败：{message}": "Screen capture failed: {message}",
    "截图失败：{exc}": "Screen capture failed: {exc}",
    "AI 分析失败：{message}": "AI analysis failed: {message}",
    "AI 分析失败：{exc}": "AI analysis failed: {exc}",
    "AI 分析失败：{error}": "AI analysis failed: {error}",
    "AI 分析异常：{message}": "AI analysis error: {message}",
    "AI 分析异常：{exc}": "AI analysis error: {exc}",
    "未配置 AI 模型，可在设置中配置后重新分析。": "AI model not configured. Set it up in Settings, then re-analyze.",
}

CATEGORY_EN: dict[str, str] = {
    "开发": "Development",
    "会议": "Meetings",
    "沟通": "Communication",
    "文档": "Documentation",
    "设计": "Design",
    "测试": "Testing",
    "运维": "Operations",
    "数据分析": "Data analysis",
    "学习": "Learning",
    "管理": "Management",
    "产品": "Product",
    "写作": "Writing",
    "研究": "Research",
    "生活": "Personal",
    "其他": "Other",
    "未分类": "Uncategorized",
    "周一": "Mon",
    "周二": "Tue",
    "周三": "Wed",
    "周四": "Thu",
    "周五": "Fri",
    "周六": "Sat",
    "周日": "Sun",
}

# 补充：并行开发中新增的遗漏文案
EN.update(
    {
        "· {open} 项未完成 / 共 {total} 项": "· {open} open / {total} total",
        "更新": "Update",
        "正在测试下载线路…": "Testing download sources…",
        "正在下载 {done}/{total} MB · {speed}/s · {source}": "Downloading {done}/{total} MB · {speed}/s · {source}",
        "已取消下载": "Download cancelled",
        "无法连接任何下载线路，请检查网络后重试": "Could not reach any download source. Check your network and try again.",
        # v0.5.2：思考模式与空内容处理
        "思考模式": "Thinking mode",
        "思考强度": "Reasoning effort",
        "默认（不指定）": "Default (not set)",
        "关闭（更快更稳定）": "Off (faster, more stable)",
        "开启": "On",
        "低": "Low",
        "高": "High",
        "最高": "Max",
        "模型把输出预算都用在思考上了（未返回内容）。请在设置 → 高级设置中关闭「思考模式」后重试。": "The model spent the whole output budget on reasoning and returned no content. Turn off \"Thinking mode\" in Settings → Advanced and try again.",
        "模型返回了空内容，请重试或在设置中调整模型。": "The model returned empty content. Please retry or adjust the model in Settings.",
        "模型输出被截断（可能把预算用在思考上），已自动重试…": "Model output was truncated (likely spent on reasoning); retrying automatically…",
    }
)
